### ISSUE TITLE
Update 6 compatibility

### ISSUE THREAD

**Issue by Marcoevich** [Timberborn-Modding-Central/TimberAPI#100]
Hello,

Will this be updated for Update 6 compatibility? If so, anything I can do to help or test it for you?

**Comment by KYPremco** [comment]
Hello @Marcoevich, thanks for reaching out.

Yes TimberApi will not yet say it's goodbye for the modding scene in Timberborn!!

But since Timberborn now has included many features it provided it will shift the project and requires a whole rework.

My priority at the moment is getting the bottombar rework + tools/groups speicifcation system, so that the 3rd layer in the bottom bar is available again.

Are you a mod user or you want to start modding yourself ?

**Comment by KYPremco** [comment]
You can always ping me in the Timberborn discord, or go to the TimberApi form under #invidual-mods->TimberApi on the discord.

**Comment by Marcoevich** [comment]
Heyy, sorry for the late reply. I'm a heavy mod user. 

I see you are indeed starting over.. must be a lot of work.

Good luck man. Thanks for all you've done for Timberborn so far!

**Comment by Marcoevich** [comment]
I have just tested your 0.7.0.0 alpha 1. I've placed it at Documents/Timberborn/Mods. I assume that's correct now?

Just wanted to let you know that it currently crashes on the latest game version. This is the crash log:

v0.6.1.2-760fc97-xsw
FileNotFoundException: Could not load file or assembly '0Harmony, Version=2.3.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Timberborn.ModManagerScene.ModCodeStarter.StartMods () (at <5d369e03796d429a8280b0a78e9ceb9d>:0)
Timberborn.ModManagerScene.ModCodeStarter.Start () (at <5d369e03796d429a8280b0a78e9ceb9d>:0)
Timberborn.ModManagerSceneUI.ModManagerScenePanel.LoadModsAndStartGame () (at <fdf558aee6ba497d913ac320167e75a5>:0)

**Comment by Marcoevich** [comment]
Hey @KYPremco, I see a developer of timberborn has now placed a Harmony mod on the steam workshop. Maybe this is helpful for you: https://steamcommunity.com/sharedfiles/filedetails/?id=3284904751

**Comment by KYPremco** [comment]
> Hey @KYPremco, I see a developer of timberborn has now placed a Harmony mod on the steam workshop. Maybe this is helpful for you: https://steamcommunity.com/sharedfiles/filedetails/?id=3284904751

Yes, I developd the mod with bepinex active. Before uploading I didn't think of this and if you just download the mod an dplace it in mods folder it will crash. If you download Harmony from mod.io or steam it should work now!

**Comment by KYPremco** [comment]
Everything that was not been implemented by the game has been converted.
