### ISSUE TITLE
U6  - Crash with Path Extension

### ISSUE THREAD

**Issue by Greytusks** [Timberborn-Modding-Central/TimberAPI#104]
@TheBloodEyes I had a break at work so I investigated a bit. 1x2 Storage was fine afterall, so I checked all mods one by one and found out that it is Path Extenion that make my loadout crash if I also have the API loaded (but no crash if the API is not loaded). Note that Knatte's other mods load fine for me and my loadout with the API loaded, only Path Extension gave me problems. I also linked this crash on his page.

Path Extension crash when TimberAPI is loaded
[error-report-2024-07-24-11h26m59s_PathExtension.zip](https://github.com/user-attachments/files/16364469/error-report-2024-07-24-11h26m59s_PathExtension.zip)

Harmony 2.3.3
TimberAPI 0.7.0.1
KnatteMaterials 1.0.2
Path Extension 2.0.0

**Comment by Greytusks** [comment]
![image](https://github.com/user-attachments/assets/b305b05f-2f9c-45e6-b36b-dc0c101b3ddd)

Normally I also enable all the other mods but for investigating this issue I enabled mods 1 by 1 with harmony and the API loaded to find which one was incompatible with the API. Not sure if the API or Path Extension is the one that needa adjustments.

**Comment by KnatteAnka** [comment]
Path extention is not latest version verify game files to get latest versions and tell if it still is not working

**Comment by Greytusks** [comment]
After forcing an update with file verification the crash no longuer occurs with v2.0.3 of PE, thanks for the tip, I didn't know you could force the mods to update thorugh that trick
