### ISSUE TITLE
Cannot launch Timberborne with 0.4.x versions of TimberAPI

### ISSUE THREAD

**Issue by AaronMountford** [Timberborn-Modding-Central/TimberAPI#23]
TimberAPI v0.4.1 and 0.4.2
Timberborne v latest as at 24-07-2022 (non-experimental)
CreativeMode v1.4.1 (disabled)
BepinEx 5.4.19
Thunderstore Mod Manager 1.16.0
Windows 11 (dev channel)

Tried using the preloader fix to no avail.

The following is logged in the console window. The game only presents a black screen, does not start at all. 

[Message:   BepInEx] BepInEx 5.4.19.0 - Timberborn (27/04/2022 4:06:10 a.m.)
[Info   :   BepInEx] Running under Unity v2021.2.14.15834644
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Creative Mode 1.4.1]
[Info   :Creative Mode] Plugin Creative Mode is loaded!
[Info   :   BepInEx] Loading [TimberAPI 0.4.2]
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly TimberAPI, Version=0.4.2.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not resolve type with token 01000046 from typeref (expected class 'Timberborn.Persistence.ISpecificationService' in assembly 'Timberborn.Persistence, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <6073cf49ed704e958b8a66d540dea948>:0
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0
System.TypeLoadException: Could not resolve type with token 01000046 from typeref (expected class 'Timberborn.Persistence.ISpecificationService' in assembly 'Timberborn.Persistence, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
[Info   : TimberAPI] Creating new asset area with prefix: timberApi
[Info   : TimberAPI] Asset timberApi/timber_api found
[Info   : TimberAPI] Prefix timberApi, assets: 1
[Info   : TimberAPI] TimberAPI is loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Starting game version 0.1.5.2-773c83b-sw
[Info   : Unity Log] System info:
System: Windows 11  (10.0.25163) 64bit
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
GPU: NVIDIA GeForce RTX 3060 Ti
GPU memory: 8050MB
RAM: 32700MB
Drives:
  C:\ 52.65GB free from 231.68GB
  E:\ 59.29GB free from 232.88GB
  F:\ 64.75GB free from 931.51GB
  G:\ 38.34GB free from 931.51GB
  H:\ 20.09GB free from 232.88GB

[Info   : Unity Log] Modded: true, BepInEx
[Info   : TimberAPI] Loading scene: Global, prefixes in scene: timberApi
[Info   : TimberAPI] Loading scene: MainMenu, prefixes in scene:
[Info   : TimberAPI] Initialized configurators for Global (First)
[Info   : TimberAPI] Initialized configurators for MainMenu (First)
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000046 from typeref (expected class 'Timberborn.Persistence.ISpecificationService' in assembly 'Timberborn.Persistence, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
Stack trace:
Bindito.Core.Internal.ContainerDefinition.Install (Bindito.Core.IConfigurator configurator) (at <97564844199c40c08db164961f62f587>:0)
TimberbornAPI.DependencySystem.DependencyRegistry.InstallAll (Bindito.Core.IContainerDefinition containerDefinition, TimberbornAPI.Common.SceneEntryPoint entryPoint, System.Boolean first) (at <b032e25b4c41417d9b859a68e412ccc7>:0)
TimberbornAPI.DependencySystem.DependencyRegistry.InjectIntoMainMenuSceneLast (Bindito.Core.IContainerDefinition containerDefinition) (at <b032e25b4c41417d9b859a68e412ccc7>:0)
(wrapper dynamic-method) Timberborn.MainMenuScene.MainMenuSceneConfigurator.DMD<Timberborn.MainMenuScene.MainMenuSceneConfigurator::Configure>(Timberborn.MainMenuScene.MainMenuSceneConfigurator,Bindito.Core.IContainerDefinition)
Bindito.Unity.SceneConfigurator.Bindito.Core.IConfigurator.Configure (Bindito.Core.IContainerDefinition containerDefinition) (at <b39f4d0e163e4a6ebf49e6ec2b083479>:0)
Bindito.Core.Internal.ConfiguratorRunner.RunConfigurators (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.ConfigureContainer (Bindito.Core.IContainer container, System.Collections.Generic.IEnumerable`1[T] configurators, Bindito.Core.Internal.IBinder binder, Bindito.Core.Internal.IProvisionListenerNotifier provisionListenerNotifier, Bindito.Core.Internal.IInjectionListenerNotifier injectionListenerNotifier) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.CreateContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.CreateChildContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.Container.CreateChildContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.Container.CreateChildContainer (Bindito.Core.IConfigurator[] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Unity.SceneConfigurator.CreateSceneContainer () (at <b39f4d0e163e4a6ebf49e6ec2b083479>:0)
Bindito.Unity.SceneConfigurator.Awake () (at <b39f4d0e163e4a6ebf49e6ec2b083479>:0)

Setting breakpad minidump AppID = 1062090
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197995687035 [API loaded no]
[Info   : Unity Log] Successfully connected to the Steam client.
[Error  : Unity Log] BindingNotFoundException: Couldn't get an instance of TimberbornAPI.PluginSystem.PluginLocationService, it wasn't bound.
Stack trace:
Bindito.Core.Internal.Container.GetInstance (System.Type type) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.Container.GetInstance[T] () (at <97564844199c40c08db164961f62f587>:0)
TimberbornAPI.ContainerSystem.ContainerHolder.GetInstance[T] () (at <b032e25b4c41417d9b859a68e412ccc7>:0)
TimberbornAPI.LocalizationSystem.LocalizationRepository.GetLocalizationFilePathsFromDependencies (System.String localizationKey) (at <b032e25b4c41417d9b859a68e412ccc7>:0)
TimberbornAPI.LocalizationSystem.LocalizationRepository.GetLocalization (System.String localizationKey) (at <b032e25b4c41417d9b859a68e412ccc7>:0)
TimberbornAPI.LocalizationSystem.Localization+LocalizationPatch.Postfix (System.String localizationKey, System.Collections.Generic.IDictionary`2[System.String,System.String]& __result) (at <b032e25b4c41417d9b859a68e412ccc7>:0)
(wrapper dynamic-method) Timberborn.Localization.LocalizationRepository.DMD<Timberborn.Localization.LocalizationRepository::GetLocalization>(Timberborn.Localization.LocalizationRepository,string)
Timberborn.Localization.LocalizationService.Load (System.String localizationCode) (at <b8c08bc0ef91476b9623fc2e69ca571e>:0)
Timberborn.Language.LanguageLoader.Load () (at <3cec79be21114748836909ac4e1ef088>:0)
Timberborn.SingletonSystem.SingletonLifecycleService.LoadSingletons () (at <db4603297ab3421687161d2315d401a3>:0)
Timberborn.SingletonSystem.SingletonLifecycleService.LoadAll () (at <db4603297ab3421687161d2315d401a3>:0)
Timberborn.SingletonSystem.SingletonLifecycleAdapter.Start () (at <db4603297ab3421687161d2315d401a3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.MainMenuScene.AutoStarter.get_AutoStartingInStandalone () (at <eac6281c786a4fb29df2668d169f3004>:0)
Timberborn.MainMenuScene.AutoStarter.StartInStandaloneMode () (at <eac6281c786a4fb29df2668d169f3004>:0)
Timberborn.MainMenuScene.AutoStarter.Start () (at <eac6281c786a4fb29df2668d169f3004>:0)

**Comment by hawkfalcon** [comment]
Use 0.3.* if you're not on experimental 🙂

**Comment by AaronBDO** [comment]
> Use 0.3.* if you're not on experimental 🙂

Simple as that, thankyou!

**Comment by AaronMountford** [comment]
Simple as that, thankyou.  Might be an idea to mention somewhere obvious in the wiki :)
