### ISSUE TITLE
Issue Starting Timberborn from Thunderstore

### ISSUE THREAD

**Issue by rheaumep** [Timberborn-Modding-Central/TimberAPI#25]
Please help! :)

[log.txt](https://github.com/Timberborn-Modding-Central/TimberAPI/files/9255566/log.txt)

**Comment by rheaumep** [comment]
Wrong document, sorry
[LogOutput.log](https://github.com/Timberborn-Modding-Central/TimberAPI/files/9255575/LogOutput.log)
!

**Comment by hytonhan** [comment]
Hello! This should be an easy fix. Judging by the logs you are playing on the stable branch and using TimberAPI v0.4.3 and CreativeMoce 1.5.0. Currently TimberAPI v0.4.x only works on experimental. Downgrade TimberAPI on v0.3.2 and it should work. On the same note I am not sure if the latest Creative Mode works on stable either, you might need to downgrade that one version back too.
