### ISSUE TITLE
Issue with Game Loading

### ISSUE THREAD

**Issue by Adthrawn** [Timberborn-Modding-Central/TimberAPI#28]
Having an issue loading the game after I had to do a timeshift back in my linux install. Using r2modman to load the mods. The Game launches fine from Steam and fine via the Start Vanilla option. The game loads to a black screen and I can see a few errors in the logs. I've attached the logs.

Couple things i've tried

* Verify game cache
* uninstall/reinstall game
* clear r2modman cache
* delete all downloaded mods/re-download

[timberborn log](https://github.com/Timberborn-Modding-Central/TimberAPI/files/9337166/timberborn.log)

**Comment by hytonhan** [comment]
Hello there!

It looks like one the the mods you are using is the ExtendedArchitecture. Unfortunately that mod is not updated (yet) to work in the experimental branch. The fix here is to disable ExtendedArchitecture.

FYI, there should be a "LogOutput.log" or similar file in either your TImberborn root or BepInEx folder, which would give the full log. You pasted log seemed to be copy-paste from the console, which sometimes cuts the beginning when there's lots of text.

**Comment by Adthrawn** [comment]
Ah, yeah that was it. ExtendedArchitecture. Thanks a lot!

I'll keep the log info in the future if there are other problems, thanks!
