### ISSUE TITLE
Pink Dirt Texture (TimberAPI 0.5.0)

### ISSUE THREAD

**Issue by KnatteAnka** [Timberborn-Modding-Central/TimberAPI#32]
When i use base game Dirt or recreated with same settings, i get Pink textures and not the expected dirt texture
if other textures is used it show up as in editor

TinyLogpile (Codeless mod atm)

Example error:
![image](https://user-images.githubusercontent.com/10638776/190925141-dfb0f914-a003-4a4e-9aee-3a72a0487590.png)
my config of the Dirt texture:
![image](https://user-images.githubusercontent.com/10638776/190925149-24d74676-d094-4ca6-87fa-b93b139b30a4.png)

Dirt:
![image](https://user-images.githubusercontent.com/10638776/190925717-8575816f-adae-4896-86e9-6be4be688c97.png)

No error in the logs.

was showing As in Editor in 0.4.4 and not the texture of base game dirt.

**Comment by KnatteAnka** [comment]
include problem mod
Showing when placing a Folktail tinylogpile
[Tinylogpile Dirt Texture.zip](https://github.com/Timberborn-Modding-Central/TimberAPI/files/9596468/Tinylogpile.Dirt.Texture.zip)

**Comment by KYPremco** [comment]
Problem solved! Thanks for the report
