### ISSUE TITLE
TimberAPI dont work

### ISSUE THREAD

**Issue by rodopoulos1** [Timberborn-Modding-Central/TimberAPI#34]
I try to run timberborn but the api dont work:

[Message:   BepInEx] BepInEx 5.4.19.0 - Timberborn (04/08/2022 14:52:34)
[Info   :   BepInEx] Running under Unity v2022.1.6.14981713
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.19.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 11 plugins to load
[Warning:   BepInEx] Plugin [Unified Factions 1.2.0] targets a wrong version of BepInEx (5.4.20.0) and might not work until you update
[Warning:   BepInEx] Plugin [FloodgateTriggersPlugin 2.0.2] targets a wrong version of BepInEx (5.4.20.0) and might not work until you update
[Warning:   BepInEx] Plugin [TimberAPI 0.4.4] targets a wrong version of BepInEx (5.4.20.0) and might not work until you update
[Info   :   BepInEx] Loading [Beaver Buffs 1.1.0]
[Warning: Unity Log] The script 'BeaverBuffs.BeaverBuffsPlugin' could not be instantiated!
[Info   :   BepInEx] Loading [Creative Mode 1.5.0]
[Info   :Creative Mode] Plugin Creative Mode is loaded!
[Info   :   BepInEx] Loading [Unified Factions 1.2.0]
[Info   :Unified Factions] Plugin Unified Factions is loaded!
[Info   :   BepInEx] Loading [TimberAPI 0.4.4]
[Info   : TimberAPI] Creating new asset area with prefix: timberApi
[Info   : TimberAPI] Asset timberApi/timber_api found
[Info   : TimberAPI] Prefix timberApi, assets: 1
[Info   : TimberAPI] TimberAPI is loaded!
[Info   :   BepInEx] Loading [DistrictExtender 1.0.0.0]
[Info   :   BepInEx] Loading [Elec.ExtendedArchitecture 0.3.0]
[Info   : TimberAPI] Creating new asset area with prefix: Elec.ExtendedArchitecture
[Info   : TimberAPI] Asset Elec.ExtendedArchitecture/elec.extendedarchitecture.bundle found
[Info   : TimberAPI] Prefix Elec.ExtendedArchitecture, assets: 1
[Info   :Elec.ExtendedArchitecture] Loaded Elec.ExtendedArchitecture 0.3.0!
[Info   :   BepInEx] Loading [FloodgateTriggersPlugin 2.0.2]
[Info   :FloodgateTriggersPlugin] FloodgateTriggersPlugin is loaded.
[Info   :   BepInEx] Loading [IrrigationTowerV2 1.0.5]
[Info   :IrrigationTowerV2] Loaded IrrigationTowerV2 Version: 1.0.5!
[Info   : TimberAPI] Creating new asset area with prefix: knatte.irrigationtowerv2
[Info   : TimberAPI] Asset knatte.irrigationtowerv2/knatte_irrigationtowerv2 found
[Info   : TimberAPI] Prefix knatte.irrigationtowerv2, assets: 1
[Info   :   BepInEx] Loading [Beaver Hats 1.0.0]
[Info   :Beaver Hats] Loaded Beaver Hats Version: 1.0.0!
[Info   : TimberAPI] Creating new asset area with prefix: tobbert.beaverhats
[Info   : TimberAPI] Asset tobbert.beaverhats/tobbert_beaverhats found
[Info   : TimberAPI] Prefix tobbert.beaverhats, assets: 1
[Info   :   BepInEx] Loading [CategoryButton 1.1.0]
[Info   :CategoryButton] Loaded CategoryButton Version: 1.1.0!
[Info   : TimberAPI] Creating new asset area with prefix: tobbert.categorybutton
[Info   : TimberAPI] Asset tobbert.categorybutton/tobbert_categorybutton found
[Info   : TimberAPI] Prefix tobbert.categorybutton, assets: 1
[Info   :   BepInEx] Loading [More Paths 1.0.0]
[Info   :More Paths] Loaded More Paths Version: 1.0.0!
[Info   : TimberAPI] Creating new asset area with prefix: tobbert.morepaths
[Info   : TimberAPI] Asset tobbert.morepaths/tobbert_morepaths found
[Info   : TimberAPI] Prefix tobbert.morepaths, assets: 1
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Starting game version 0.2.7.0-a1bd505-xsw
[Info   : Unity Log] System info:
System: Windows 10  (10.0.19044) 64bit
CPU: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
GPU: Intel(R) HD Graphics 5000
GPU memory: 2048MB
RAM: 8132MB
Drives:
  C:\ 50.48GB free from 344.37GB
  D:\ 85.44GB free from 121.35GB

[Info   : Unity Log] Modded: true, BepInEx
[Info   : TimberAPI] Loading scene: Global, prefixes in scene: timberApi,Elec.ExtendedArchitecture,knatte.irrigationtowerv2
[Info   : TimberAPI] Loading scene: MainMenu, prefixes in scene:
[Info   : TimberAPI] Initialized configurators for Global (First)
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 0100000c from typeref (expected class 'Timberborn.SingletonSystem.IInitializableSingleton' in assembly 'Timberborn.SingletonSystem, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
Stack trace:
Bindito.Core.Internal.ContainerDefinition.Install (Bindito.Core.IConfigurator configurator) (at <97564844199c40c08db164961f62f587>:0)
TimberbornAPI.DependencySystem.DependencyRegistry.InstallAll (Bindito.Core.IContainerDefinition containerDefinition, TimberbornAPI.Common.SceneEntryPoint entryPoint, System.Boolean first) (at <ce0ecb323c63403bba20e2c43f498687>:0)
TimberbornAPI.DependencySystem.DependencyRegistry.InjectIntoMainMenuSceneFirst (Bindito.Core.IContainerDefinition containerDefinition) (at <ce0ecb323c63403bba20e2c43f498687>:0)
(wrapper dynamic-method) Timberborn.MainMenuScene.MainMenuSceneConfigurator.DMD<Timberborn.MainMenuScene.MainMenuSceneConfigurator::Configure>(Timberborn.MainMenuScene.MainMenuSceneConfigurator,Bindito.Core.IContainerDefinition)
Bindito.Unity.SceneConfigurator.Bindito.Core.IConfigurator.Configure (Bindito.Core.IContainerDefinition containerDefinition) (at <ec631eb0d25c4c4db7fbbd81a101ffcc>:0)
Bindito.Core.Internal.ConfiguratorRunner.RunConfigurators (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.ConfigureContainer (Bindito.Core.IContainer container, System.Collections.Generic.IEnumerable`1[T] configurators, Bindito.Core.Internal.IBinder binder, Bindito.Core.Internal.IProvisionListenerNotifier provisionListenerNotifier, Bindito.Core.Internal.IInjectionListenerNotifier injectionListenerNotifier) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.CreateContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.ContainerCreator.CreateChildContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.Container.CreateChildContainer (System.Collections.Generic.IEnumerable`1[T] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.Container.CreateChildContainer (Bindito.Core.IConfigurator[] configurators) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Unity.SceneConfigurator.CreateSceneContainer () (at <ec631eb0d25c4c4db7fbbd81a101ffcc>:0)
Bindito.Unity.SceneConfigurator.Awake () (at <ec631eb0d25c4c4db7fbbd81a101ffcc>:0)

[Info   : Unity Log] Successfully connected to the Steam client.
[Error  : Unity Log] BindingNotFoundException: Couldn't get an instance of TimberbornAPI.PluginSystem.PluginLocationService, it wasn't bound.
Stack trace:
Bindito.Core.Internal.Container.GetInstance (System.Type type) (at <97564844199c40c08db164961f62f587>:0)
Bindito.Core.Internal.Container.GetInstance[T] () (at <97564844199c40c08db164961f62f587>:0)
TimberbornAPI.ContainerSystem.ContainerHolder.GetInstance[T] () (at <ce0ecb323c63403bba20e2c43f498687>:0)
TimberbornAPI.LocalizationSystem.LocalizationRepository.GetLocalizationFilePathsFromDependencies (System.String localizationKey) (at <ce0ecb323c63403bba20e2c43f498687>:0)
TimberbornAPI.LocalizationSystem.LocalizationRepository.GetLocalization (System.String localizationKey) (at <ce0ecb323c63403bba20e2c43f498687>:0)
TimberbornAPI.LocalizationSystem.Localization+LocalizationPatch.Postfix (System.String localizationKey, System.Collections.Generic.IDictionary`2[System.String,System.String]& __result) (at <ce0ecb323c63403bba20e2c43f498687>:0)
(wrapper dynamic-method) Timberborn.Localization.LocalizationRepository.DMD<Timberborn.Localization.LocalizationRepository::GetLocalization>(Timberborn.Localization.LocalizationRepository,string,bool)
Timberborn.Localization.LocalizationService.Load (System.String localizationCode) (at <da209a9f5406406c9870d04421ae39db>:0)
Timberborn.Language.LanguageLoader.Load () (at <8a10da8a91954dfc9587eff54aba9134>:0)
Timberborn.SingletonSystem.SingletonLifecycleService.LoadSingletons () (at <6e2ec85adbc24a7185ecd28e81dcfab6>:0)
Timberborn.SingletonSystem.SingletonLifecycleService.LoadAll () (at <6e2ec85adbc24a7185ecd28e81dcfab6>:0)
Timberborn.SingletonSystem.SingletonLifecycleAdapter.Start () (at <6e2ec85adbc24a7185ecd28e81dcfab6>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.MainMenuScene.AutoStarter.get_AutoStartingInStandalone () (at <30688a2091dc4c1db148186319bbbf8b>:0)
Timberborn.MainMenuScene.AutoStarter.StartInStandaloneMode () (at <30688a2091dc4c1db148186319bbbf8b>:0)
Timberborn.MainMenuScene.AutoStarter.Start () (at <30688a2091dc4c1db148186319bbbf8b>:0)

**Comment by KnatteAnka** [comment]
This is not a problem with timber api but using outdated mod beaverbuff see https://docs.google.com/spreadsheets/d/15juA0Fl6ZjbYmoNTg_vjMophBvtjMz8YNUI_KmNdtdg/edit?usp=drivesdk for supported mods!
