### ISSUE TITLE
DependencyRegistry doesn't exist in TimbeApi

### ISSUE THREAD

**Issue by joemoney** [Timberborn-Modding-Central/TimberAPI#35]
I'm trying to make a mod and installed everything according to the guide. But when I tried to register a configurator Visual Studio intellisense says that DependencyRegistry doesn't exist

attached is the screenshot with the installed packages in my IDE
![image](https://user-images.githubusercontent.com/11543313/192168924-7b7ef9eb-d33b-49b9-851e-dab916638e9f.png)

**Comment by hawkfalcon** [comment]
We need to update the wiki/docs… sorry. This week we released v0.5 and things changed. We now have an annotation!

**Comment by hawkfalcon** [comment]
[Configurator(SceneEntrypoint.InGame)]

**Comment by joemoney** [comment]
Thanks for the quick feedback. I'll just wait for the updated documentation for TimberApi 5.0
