### ISSUE TITLE
Not compatible with experimental update

### ISSUE THREAD

**Issue by RubenDefour** [Timberborn-Modding-Central/TimberAPI#43]
The version of TimberAPI is not yet compatible with the experimental version of timberborn.

**Comment by KYPremco** [comment]
I labeled as wontfix so other people don't have to make another issue.

TimberAPI has been fixed in [PR#41l fix](https://github.com/Timberborn-Modding-Central/TimberAPI/pull/41) but we'll skip this experimental version for now until all other delayed items are finished.

**Comment by RubenDefour** [comment]
thx for the update. No worries i'll wait for the next real update of the game :D

**Comment by KYPremco** [comment]
Sadly it broke again :), in the future this it might be easier to update when all automation is back online.
