### ISSUE TITLE
Fix style

### ISSUE THREAD

**Issue by hytonhan** [Timberborn-Modding-Central/TimberAPI#44]
Game version 0.2.9(?) or so broke some TAPI uss styles. When using the UI Builder to add an item that has a scrollbar, it will throw a warning and the scrollbars won't show
```
[Warning: Unity Log] Image not found for path: UI/Images/Core/scroll_bar
[Warning: Unity Log] Image not found for path: UI/Images/Core/scroll_bar
[Warning: Unity Log] Image not found for path: UI/Images/Core/scroll_button
```

msg by pmduda: "pmduda: they were replaced with scroll-bar-nine-slice and scroll-button-nine-slice" (https://discord.com/channels/558398674389172225/888491376143134760/1029793624151564429)

**Comment by KYPremco** [comment]
Since it's a nine-sliced version now this might be possible to fix programmaticly

**Comment by KYPremco** [comment]
This is way to long open... now update 6 has arrived it will be included with the UIBuilder rework and will be easier to fix in the future.
