### ISSUE TITLE
Functionality to save config with TimberAPI

### ISSUE THREAD

**Issue by hytonhan** [Timberborn-Modding-Central/TimberAPI#48]
I as a modder want to have a method provided by TimberAPI to save the Configs I've created, so that I don't have to do custom code for config saving

**Comment by hytonhan** [comment]
No, that line reads the config from file, or creates the file if it doesn't exist. With this issue I mean functionality that a modder could call something like Config.Save(), which would overwrite the config. This would enable changing configs from in-game. I made something like that in the RotatingSun https://github.com/hytonhan/Timberborn-RotatingSun/blob/c3a932a9e632711532b0d0db70d31dc07ca8392c/RotatingSunPlugin.cs#L99

**Comment by thomaswp** [comment]
Adding a +1 to this. My mod reads a value for the config and allows the user to modify it in-game. It would be great if I could persist that value, so they don't need to update it the second time.

**Comment by KYPremco** [comment]
Sorry that this never came to be, and now never will. Configs should be used with `Mod Settings mod`.
