### ISSUE TITLE
Why marked as deprecated?

### ISSUE THREAD

**Issue by Marcoevich** [Timberborn-Modding-Central/TimberAPI#50]
TimberAPI is afaik the go-to API for Timberborn modding. I see it is marked as deprecated on Thunderstore and the mods that depend on it as well. Why is that? Is an alternative being developed? 

I'm in the process of creating a new mod based on TimberAPI so I would like to know before I build something that's outdated from the start.

Thanks

**Comment by hawkfalcon** [comment]
Thunderstore itself is deprecated. You can find it on mod.io now :)

**Comment by Marcoevich** [comment]
Good to know. Thanks! :)
