### ISSUE TITLE
Suggestion: warning mod missing when load

### ISSUE THREAD

**Issue by KnatteAnka** [Timberborn-Modding-Central/TimberAPI#63]
Is it possible to give warning if save have had a mod installed and is removed? (@KYPremco  said yes)

at save saves list of mods and versions used 
At load compare the list when loading show warning if any mods is missing and what version used.

Include mods and versions in save in log so if it crash you know what versions was used?

**Comment by KYPremco** [comment]
This should be handled now by the base game. Although I have not seen it yet 🤔.
