### ISSUE TITLE
Update 5.5.3^ bugs

### ISSUE THREAD

**Issue by KYPremco** [Timberborn-Modding-Central/TimberAPI#72]
- [x] Missing ruins in MapEditor, make the basePatcher unpatch/patch on scene switch with the sceneManager
- [x] Adding new recipes to building, InventoryDedicator loads before building specifications are generated.
- [x] Order changing after reload, generated specifications need to be globally cached
- [ ] ~~ApiResourceLoader meshy not working. Needs to check if T is MeshyBinary if so load the gameObject instead and return the binary with getComponent.~~
- [x] Remove empty groups

**Comment by KnatteAnka** [comment]
- [ ] Tool order is incorrect:
Current TAPI `Mark resources for demolision | Demolish Buildings | Cancel `
Should be: `Demolish Buildings | Mark resources for demolision |  Cancel ` ( mark and Demolish building is swaped)
Example of base game:
![image](https://github.com/Timberborn-Modding-Central/TimberAPI/assets/10638776/6307d8dd-e055-46a1-bb1f-578dab250d18)

**Comment by KnatteAnka** [comment]
Clarification:
Current TAPI (Dev mode)
![image](https://github.com/Timberborn-Modding-Central/TimberAPI/assets/10638776/06298a25-8f17-4a77-a4c1-3d04fcbb4f50)
`Mark resources for demolition | Demolish Buildings |  Demolish Objects (Dev mode) | Cancel`

BaseGame (Dev mode)
![image](https://github.com/Timberborn-Modding-Central/TimberAPI/assets/10638776/606f35be-39b1-4e8a-8f77-27e8b009e249)
` Demolish Buildings | Mark resources for demolition | Demolish Objects (Dev mode) | Cancel`

Suggested Order:s
| ID                        | Order (current) | Icon                  |
|---------------------------|-------|-----------------------|
| EntityBlockObjectDeletion | 300  (20) | DeleteObjectIcon      (Dev mode)![DeleteObjectIcon](https://github.com/Timberborn-Modding-Central/TimberAPI/assets/10638776/0cc098da-7e15-4b93-bce3-eed6be832f1e)  |
| BuildingDeconstruction    | 20   (10) | DeleteObjectIcon            ![DeleteObjectIcon](https://github.com/Timberborn-Modding-Central/TimberAPI/assets/10638776/0cc098da-7e15-4b93-bce3-eed6be832f1e)  |
| DemolishableSelection     | 100  (0) | DemolishResourcesTool ![DemolishResourcesTool](https://github.com/Timberborn-Modding-Central/TimberAPI/assets/10638776/fe4ba320-d4c7-4a2d-af08-00db5a5694e3) |
| DemolishableUnselection   | 1000  (1000)| CancelToolIcon       ![CancelToolIcon](https://github.com/Timberborn-Modding-Central/TimberAPI/assets/10638776/7c87606e-0a3d-449c-ad51-9afc92bf20c2)  |

Note that Beaver and but buttons is added

**Comment by KYPremco** [comment]
Meshy will be implemented when people are able to use it correcrly
