### ISSUE TITLE
Add onEnable/onDisable for mods to use during gameplay

### ISSUE THREAD

**Issue by awsdert** [Timberborn-Modding-Central/TimberAPI#83]
Instead of having to reboot the entire game to enable/disable mods it would be nice if there was something they could use to say "We can be enabled/disabled during gameplay without issue". I'm guessing you'd have to work with the Mod Manager Mod devs to work out what the best way of doing this is but I & many others will appreciate not having to fully re-boot the game each time we only enable/disable a minor mod like "More platforms" for example. It's fine to need to re-boot after installing/removing mods for bepinex to notice them but when just enabling/disabling them it would be nice for them to just wait for TAPI to tell them to either enable/disable themselves rather then automatic enable at boot of the game.

**Comment by awsdert** [comment]
Since we discussed it a lot on the mod's channel (on discord for those not in the know) I figured I should copy paste the most reasonable implementation I could think of at the end of that thread so that other peops who come to this thread at least understand the expected scope of the feature better:

> It means, you grab the pointer or whatever is provided for listing mod that are enabled - such as just looking through the directory for non-disabled mods and then identifying their libraries and doing a "findmodule" (which I know win32 provides)  to grab it's handle, do a quick scan with FindProcAddress or whatever it was called for the expected functions, if not found then drop the handle and move on, if it does then generate a checkbox in the list with the name of the mod next to it, when it's toggled just call the right function to match and bob's your uncle you have your "one and done" feature

**Comment by KYPremco** [comment]
As concluded from the discussion this is not something that should and would be implemented in TimberApi and modders are able to do this themself already but have decided not to do so. But something similar to this feature would be possible if we build the UI for the configs.

**Comment by awsdert** [comment]
Well if you make it something TAPI searches for modders would be more inclined to implement it since players who notice the feature will then ask the modders why they haven't implemented it, has the added benefit of giving the Mod Manager a pair of functions to look for to limit the need to reboot the entire game. I'm not saying TAPI has to mandate the function be there, just define with a common UI what modders should define if they plan to support the feature. Almost nothing get's done in society until something drags it into the limelight, that's why I want TAPI to drag the feature into the limelight with this simple UI addition.

**Comment by KYPremco** [comment]
That is like saying.. Oh the wheel is already invented but because this random local shop owner needs to create his own wheel else it won't get used by society...

This is not so big of a deal unless you want to swap mods every hour. Restarting with different mod setups is very common, Minecraft, Factorio, Subnautica, Beatsaber. Probably the only games that don't need it are build-in mods just for extra content, which still require a reload of the save game, reloading the whole game in Timberborn takes 2 seconds more.

But you are free to make an API that already exists and upload it to mod.io or make an PR since it's very quick and easy to do. Just add a pointer and search all mods and it's fixed

**Comment by awsdert** [comment]
Does NOT take just 2 seconds more, for me it takes about half a minute if steam is already booted and a full minute if it's not, dunno what caused that but I bet there's plenty of other gamers out there with the same problem and would very much appreciate being about to enable/disable mods during runtime to see what mod is causing the issue they've run into with something. Also your example sucks, a better example would be `The wheel already being invented but some people need a smoother ride than what hard stone/wood wheels provide...` Which would better represent why this feature needs to be added. Just admit it, you're looking for any excuse to not implement it because you can't be bothered, I don't strike issue with you not being bothered to do it but don't create bullshit excuses for it, just own up to it like a normal human being, you would've looked better for it than how you now do because of those crappy excuses.

**Comment by hawkfalcon** [comment]
Woah. The entitlement is real. We're all volunteers here, working for free. We don't HAVE to do anything, we create because it's fun and we want to. Have some respect.

**Comment by KYPremco** [comment]
If the issue is such a simple request and too easy to make it. Why are you making excuses and complaining instead of just making it yourself. Don't be lazy and make an PR or create a mod for it. It is that easy.

I told you many times that I don't want to be bothered with it. Since it cost way too much time and maintance just so you can have 30 second faster more time every few months there is a big update. But you don't know how to make this "feature" in a good state and think it's just a simple method that needs to be added. Which IF WANTED ALREADY IS POSSIBLE.

**Comment by awsdert** [comment]
> Woah. The entitlement is real. We're all volunteers here, working for free. We don't HAVE to do anything, we create because it's fun and we want to. Have some respect.

Where was the entitlement? I said giving excuses for not being bothered makes a person look bad, just coming out and saying you can't be bothered would've annoyed me sure but I would've at least respected kypremo for it, instead I now respect him less for giving excuses when he coulda just be honest.

**Comment by awsdert** [comment]
> If the issue is such a simple request and too easy to make it. Why are you making excuses and complaining instead of just making it yourself. Don't be lazy and make an PR or create a mod for it. It is that easy.

I AM lazy though, I didn't make any excuses for that, besides TAPI is where the feature belongs, not another mod that has a high chance of not being acknowledged by other modders to begin with.
 
> I told you many times that I don't want to be bothered with it

Where exactly did you say you could not be bothered? You just gave excuses for not doing it, trying to say it didn't belong in TAPI so you'd have an excuse to refuse it instead of just coming out and saying something along the lines of "I can't be bothered, maybe I'll do it in the future but definitely not now"

> Since it cost way too much time and maintance just so you can have 30 second faster more time every few months there is a big update. But you don't know how to make this "feature" in a good state and think it's just a simple method that needs to be added. Which IF WANTED ALREADY IS POSSIBLE.

What maintenance is there in re-using the very same functions you use to open the directly and identify libraries to plugin to then call `GetModuleHandleA`/`GetModuleHandleW` to check if it's been loaded then call `GetProcAddress` to see if whatever you define `enabled`/`enable`/`disable` functions as are provided and then use the very same UI functions you already have to display a checkbox with the mod's name next to it (which I'm sure your existing functions can already identify) and simply match the state of the checkbox to the result of the `enabled` function and use the `enable`/`disable` equivalents when the checkbox is toggled?

0, nata, none, nothing, etc. Face it, you gave an excuse I saw right through because I have experience in programming on windows. Because I understood you already have 99% of what you need to add the feature once and forget about it permanently. Because while I'm too lazy to hunt through your code for where to add it and submit a patch, I'm not too lazy to think about how it would be implemented in a "place once and forget" just llike the number crunchers of the iron teeth beavers, or the automatic pumps, or the windmills, or the gravity batteries, or the flywheels.

I will readily admit I'm too lazy for it and I would've accepted it (albeit begrudgingly) if you had just directly said you couldn't be bothered, instead you tried to weazle out it with excuses.

**Comment by KYPremco** [comment]
k
