### ISSUE TITLE
Error loading Timberborn Update 5

### ISSUE THREAD

**Issue by Tharnadar** [Timberborn-Modding-Central/TimberAPI#90]
Hi guys, I installed this mod via ModManager https://mod.io/g/timberborn/m/simplefloodgatetriggers because I've seen this YT video https://www.youtube.com/watch?v=PxnLzMp5zU8 about the mod, and it works flawless.

That mod has a dependency with TimberAPI mod, and when I launch the game I got the following error

```
[Message:   BepInEx] BepInEx 5.4.21.0 - Timberborn (03/11/2023 15:58:46)
[Info   :   BepInEx] Running under Unity v2023.1.16.15052116
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Mod Manager UI 1.2.4]
[Info   :   BepInEx] Loading [TimberAPI BepInEx Entrypoint 1.0.0]
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000053 from typeref (expected class 'Timberborn.InputSystem.KeyboardController' in assembly 'Timberborn.InputSystem, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
Stack trace:
TimberApi.Common.Helpers.PrefabBuilder.AddGameObject (System.String name, System.Action 1[T] gameObjectBuilder) (at <b50aca4c59c34ac4b8c6cff6274fd725>:0)
TimberApi.Core.ConsoleSystem.ConsoleSystemConfigurator.Prefab (UnityEngine.GameObject parent) (at <2bf926689de749029d733b0402afa250>:0)
TimberApi.Core.BootstrapSystem.TimberApiBootstrapSystemConfigurator.AddPrefabConfigurators () (at <2bf926689de749029d733b0402afa250>:0)
TimberApi.Core.BootstrapSystem.TimberApiBootstrapSystemConfigurator.Awake () (at <2bf926689de749029d733b0402afa250>:0)
UnityEngine.GameObject:AddComponent()
TimberApi.Core.Startup:Run()
System.Reflection.MethodBase:Invoke(Object, Object[])
TimberApi.BepInExPlugin.Loader.BaseStartupLoader:LoadAndInitializeCoreStartup()
TimberApi.BepInExPlugin.Loader.BepInExStartupLoader:Run(String)
TimberApi.BepInExPlugin.Loader.TimberApiPluginEntrypoint:GameStartLoggerLogPatch()
Timberborn.Core.GameStartLogger:DMD<Timberborn.Core.GameStartLogger::Log>()

[Info   : Unity Log] Starting game version 0.5.2.1-e167784-xsw
[Info   : Unity Log] System info:
System: Windows 11  (10.0.22000) 64bit
CPU: AMD Ryzen 5 3600 6-Core Processor
GPU: Radeon RX 570 Series
GPU memory: 4075MB
RAM: 16309MB
Drives:
  C:\ 339.37GB free from 930.76GB
  D:\ 0.10GB free from 0.54GB
  G:\ 15.55GB free from 118.20GB

[Info   : Unity Log] Modded: true, BepInEx
Setting breakpad minidump AppID = 1062090
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198011002537 [API loaded no]
[Info   : Unity Log] Successfully connected to the Steam client.
[Info   :Mod Manager UI] Loaded 29 custom labels
[Info   : Unity Log] Previous resolution: 1920 x 1200
New resolution 1920 x 1200
Display resolution: 1920 x 1200
Full screen: True
Graphics quality: Ultra
Resolution scale: 1
```

Do you have any clue about the issue?

**Comment by IzaacJ** [comment]
I experience the same issue on the latest experimental. Very sad since I also went for the same mod due to Skye and his amazing series

**Comment by Evilbolzen** [comment]
I managed to get mods working again, I also wanted to check out update 5 like Skye showed in his vids ;) 

Here is what I did:

- uninstall all mods (keep bebinex and the modmanager)
- Ingame, go to the mod manager. Select the mod you want but DON'T click download on overview site. Open the mod specific detailed site instead. Select the highest version available in the dropdown (usually higher than the current live version that you would download by pressing download in the mods-overview).
- Do this for TimerAPI and the Modmanager as well. For me, the game crashed when I wanted to exit the mod manager, however, RESTART the game anyways.
- Now launch a new game or load a save, DON'T OPEN THE MODBROWSER AGAIN. It should have the mods included now.

I did one thing additionally but I don't think it's related to the fix was installing tbmpl-core from the ModBrowser as well.

Hope this helps you guys......I'll have to re-route some water now ;)

**Comment by KYPremco** [comment]
> I managed to get mods working again, I also wanted to check out update 5 like Skye showed in his vids ;)
> 
> Here is what I did:
> 
> * uninstall all mods (keep bebinex and the modmanager)
> * Ingame, go to the mod manager. Select the mod you want but DON'T click download on overview site. Open the mod specific detailed site instead. Select the highest version available in the dropdown (usually higher than the current live version that you would download by pressing download in the mods-overview).
> * (OPT: Make sure BepinEx is also the highest version available, for me it was already the case)
> * Do this for TimerAPI and the Modmanager as well. For me, the game crashed when I wanted to exit the mod manager, however, RESTART the game anyways.
> * Now launch a new game or load a save, DON'T OPEN THE MODBROWSER AGAIN. It should have the mods included now.
> 
> I did one thing additionally but I don't think it's related to the fix was installing tbmpl-core from the ModBrowser as well.
> 
> Hope this helps you guys......I'll have to re-route some water now ;)

This is indeed correct, the active version on mod.io (which is downloaded by the mod manager) will never be compatible with an experimental branch. Unless the game somehow did not break the mod.
