### ISSUE TITLE
Error starting game with latest 11/13 update

### ISSUE THREAD

**Issue by btodoroff** [Timberborn-Modding-Central/TimberAPI#91]
Only mod is SimpleFloodgateTriggers and dependencies with all latest versions as of posting this.  Hope it helps with adapting to latest patch for a great mod.

[error-report-2023-11-13-09h39m09s.zip](https://github.com/Timberborn-Modding-Central/TimberAPI/files/13339223/error-report-2023-11-13-09h39m09s.zip)

[Message:   BepInEx] BepInEx 5.4.22.0 - Timberborn (11/13/2023 9:14:39 AM)
[Info   :   BepInEx] Running under Unity v2023.1.18.2843550
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Mod Manager UI 1.2.4]
[Info   :   BepInEx] Loading [TimberAPI BepInEx Entrypoint 1.0.0]
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Starting game version 0.5.3.0-b1d2ff8-xsw
[Info   : Unity Log] System info:
System: Windows 10  (10.0.19045) 64bit
CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
GPU: NVIDIA GeForce GTX 1060 6GB
GPU memory: 6043MB
RAM: 32658MB
Drives:
  C:\ 178.65GB free from 464.68GB
  D:\ 1774.50GB free from 1863.00GB
  G:\ 12.63GB free from 15.00GB
  W:\ 1023.98GB free from 1024.00GB
  X:\ 294.66GB free from 931.50GB
  Y:\ 20564.17GB free from 21208.26GB

[Info   : Unity Log] Modded: true, BepInEx
[Info   :TimberAPI Core] TimberAPI 0.6.2.1 - Timberborn 0.5.3.0, loader: BepInEx
[Info   : TimberAPI] Mod loading started
[Info   : TimberAPI] Found 1 mods
[Info   : TimberAPI] Deserialized 1 mods
[Info   :FloodgateTriggersPlugin] FloodgateTriggersPlugin is loaded.
[Info   :FloodgateTriggersPlugin] Loaded version 4.0.4.0
[Info   : TimberAPI] Mod loading finished in: 28ms, Loaded mods:1
[Info   : TimberAPI] Added 1 prefixes
Setting breakpad minidump AppID = 1062090
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197998718878 [API loaded no]
[Info   : Unity Log] Successfully connected to the Steam client.
[Info   :Mod Manager UI] Loaded 29 custom labels
[Info   : TimberAPI] Loaded 45 custom labels
[Info   : TimberAPI] Assets loaded for MainMenu, Total prefixes loaded: 1
[Info   : Unity Log] Previous resolution: 1920 x 1200
New resolution 1920 x 1200
Display resolution: 1920 x 1200
Full screen: True
Graphics quality: Ultra
Resolution scale: 1
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type Timberborn.ToolSystem.ToolButton and name OnButtonClicked and parameters
[Error  : TimberAPI] Patcher TimberApi.ToolButton failed.
System.NullReferenceException: Null method for TimberApi.ToolButton
  at HarmonyLib.PatchProcessor.Patch () [0x0001d] in <474744d65d8e460fa08cd5fd82b5d65f>:0
  at HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer, HarmonyLib.HarmonyMethod ilmanipulator) [0x00031] in <474744d65d8e460fa08cd5fd82b5d65f>:0
  at HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer) [0x00000] in <474744d65d8e460fa08cd5fd82b5d65f>:0
  at TimberApi.BottomBarSystem.Patchers.ToolButtonPatcher.Apply (HarmonyLib.Harmony harmony) [0x00019] in <35cb4dad646f4fb4a4151c6d6208b7e3>:0
  at TimberApi.HarmonyPatcherSystem.HarmonyPatcherActivator.PatchAll (System.Nullable`1[T] scene) [0x0004b] in <35cb4dad646f4fb4a4151c6d6208b7e3>:0
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type Timberborn.ToolSystem.ToolGroupButton and name ContainsTool and parameters
[Error  : TimberAPI] Patcher TimberApi.ToolGroupButton failed.
System.NullReferenceException: Null method for TimberApi.ToolGroupButton
  at HarmonyLib.PatchProcessor.Patch () [0x0001d] in <474744d65d8e460fa08cd5fd82b5d65f>:0
  at HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer, HarmonyLib.HarmonyMethod ilmanipulator) [0x00031] in <474744d65d8e460fa08cd5fd82b5d65f>:0
  at HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer) [0x00000] in <474744d65d8e460fa08cd5fd82b5d65f>:0
  at TimberApi.BottomBarSystem.Patchers.ToolGroupButtonPatcher.Apply (HarmonyLib.Harmony harmony) [0x00019] in <35cb4dad646f4fb4a4151c6d6208b7e3>:0
  at TimberApi.HarmonyPatcherSystem.HarmonyPatcherActivator.PatchAll (System.Nullable`1[T] scene) [0x0004b] in <35cb4dad646f4fb4a4151c6d6208b7e3>:0
[Info   :   Console] Day in secs: 460
[Info   : TimberAPI] Assets unloaded for MainMenu
[Info   : TimberAPI] Assets loaded for InGame, Total prefixes loaded: 1
[Info   : Unity Log] Starting new game at 2023-11-13 09:39:07Z:
FactionId: IronTeeth, MapFileReference: Name: Waterfalls, Resource: True, NewGameMode: StartingAdults: 8
AdultAgeProgress: Min: 0.1, Max: 0.7
StartingChildren: 4
ChildAgeProgress: Min: 0.1, Max: 0.8
FoodConsumption: 1
WaterConsumption: 1
StartingFood: 130
StartingWater: 0
TemperateWeatherDuration: Min: 13, Max: 17
DroughtDuration: Min: 5, Max: 9
DroughtDurationHandicapMultiplier: 0.38
DroughtDurationHandicapCycles: 6
CyclesBeforeRandomizingBadtide: 3
ChanceForBadtide: 0.4
BadtideDuration: Min: 5, Max: 9
BadtideDurationHandicapMultiplier: 0.38
BadtideDurationHandicapCycles: 6
InjuryChance: 1
DemolishableRecoveryRate: 0.75
[Info   : Unity Log] Previous resolution: 1920 x 1200
New resolution 1920 x 1200
Display resolution: 1920 x 1200
Full screen: True
Graphics quality: Ultra
Resolution scale: 1
[Error  : Unity Log] MissingMethodException: Method not found: void Timberborn.ToolSystem.ToolGroupButton..ctor(Timberborn.Localization.ILoc,Timberborn.ToolSystem.ToolGroup,UnityEngine.UIElements.VisualElement,UnityEngine.UIElements.VisualElement,UnityEngine.UIElements.VisualElement)
Stack trace:
TimberApi.ToolGroupUISystem.ToolGroupButtonFactory.Create (Timberborn.ToolSystem.ToolGroup toolGroup, UnityEngine.Sprite toolGroupImage, System.String backgroundImage) (at <35cb4dad646f4fb4a4151c6d6208b7e3>:0)
TimberApi.ToolGroupUISystem.Factories.ToolGroupButtonGreenFactory.Create (TimberApi.ToolGroupSystem.IToolGroup toolGroup, Timberborn.ToolSystem.ToolGroupSpecification toolGroupSpecification) (at <35cb4dad646f4fb4a4151c6d6208b7e3>:0)
TimberApi.ToolGroupSystem.ToolGroupService.LateLoad () (at <35cb4dad646f4fb4a4151c6d6208b7e3>:0)
TimberApi.Core.SingletonSystem.SingletonSystemPatcher+<>c.<LoadSingletonsPostfix>b__5_0 (TimberApi.Common.SingletonSystem.ILateLoadableSingleton singleton) (at <bc837137619e4879b463c86889372bcc>:0)
TimberApi.Core.SingletonSystem.SingletonSystemPatcher.LoadSingleton[T] (System.Collections.Generic.IEnumerable`1[T] singletons, System.Action`1[T] action) (at <bc837137619e4879b463c86889372bcc>:0)
TimberApi.Core.SingletonSystem.SingletonSystemPatcher.LoadSingletonsPostfix (Timberborn.SingletonSystem.ISingletonRepository ____singletonRepository) (at <bc837137619e4879b463c86889372bcc>:0)
(wrapper dynamic-method) Timberborn.SingletonSystem.SingletonLifecycleService.DMD<Timberborn.SingletonSystem.SingletonLifecycleService::LoadSingletons>(Timberborn.SingletonSystem.SingletonLifecycleService)
(wrapper dynamic-method) Timberborn.SingletonSystem.SingletonLifecycleService.DMD<Timberborn.SingletonSystem.SingletonLifecycleService::LoadAll>(Timberborn.SingletonSystem.SingletonLifecycleService)
Timberborn.SingletonSystem.SingletonLifecycleAdapter.Start () (at <af9416b90c6d4b6bb2f2a1c5dbed77c9>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Timberborn.CoreUI.PanelStack.Awake () (at <57dbc42f8805424f9f1e4467b243c7ae>:0)

[Info   :Mod Manager UI] Loaded 29 custom labels
[Info   : TimberAPI] Loaded 45 custom labels
[Info   : Unity Log] Creating an error report: C:\Users\brian\Documents\Timberborn\Error reports\error-report-2023-11-13-09h39m09s.zip
[Info   : Unity Log] Load time: 4582ms
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
UnityEngine.Component.get_gameObject () (at <fe5da7bf138e4fe086b7b29cbdb30e52>:0)
Timberborn.GameSound.GameMusicPlayer.PlaySound (System.String soundName, System.Action callback, System.Nullable`1[T] delay) (at <0906f1f79b2944b29d6626ba0d08a7da>:0)
Timberborn.GameSound.GameMusicPlayer.StartStandardMusic () (at <0906f1f79b2944b29d6626ba0d08a7da>:0)
Timberborn.GameSound.GameMusicPlayer.OnSceneLoaded (System.Object sender, System.EventArgs e) (at <0906f1f79b2944b29d6626ba0d08a7da>:0)
Timberborn.SceneLoading.SceneLoader+<LoadSceneCoroutine>d__15.MoveNext () (at <26d28db235864b7184fa2cb9e07290d5>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <fe5da7bf138e4fe086b7b29cbdb30e52>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
UnityEngine.Component.get_gameObject () (at <fe5da7bf138e4fe086b7b29cbdb30e52>:0)
Timberborn.GameSound.GameMusicPlayer.PlaySound (System.String soundName, System.Action callback, System.Nullable`1[T] delay) (at <0906f1f79b2944b29d6626ba0d08a7da>:0)
Timberborn.GameSound.GameMusicPlayer.StartStandardMusic () (at <0906f1f79b2944b29d6626ba0d08a7da>:0)
Timberborn.GameSound.GameMusicPlayer.OnSceneLoaded (System.Object sender, System.EventArgs e) (at <0906f1f79b2944b29d6626ba0d08a7da>:0)
Timberborn.SceneLoading.SceneLoader+<LoadSceneCoroutine>d__15.MoveNext () (at <26d28db235864b7184fa2cb9e07290d5>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <fe5da7bf138e4fe086b7b29cbdb30e52>:0)

**Comment by KYPremco** [comment]
Try using version 0.6.3.0

**Comment by KYPremco** [comment]
Duo no further response this issue is closed.
