### ISSUE TITLE
Timberborn.Workshops.ObservatoryAnimator no longer exists in v5, but still exists in TimberAPI

### ISSUE THREAD

**Issue by thomaswp** [Timberborn-Modding-Central/TimberAPI#97]
It seems the class Timberborn.Workshops.ObservatoryAnimator was removed or moved in v5, but TimberAPI still shows it. I'm not sure if that's for backwards compatibility, but since the class doesn't exist in the game, I don't think there's any reason to keep it around in the API.

Thanks for your great work!

**Comment by KYPremco** [comment]
This is not included in TimberApi but the gamelibs of Timberborn itself. They either still use this for some other components or forgot to remove it.

This is for anything related to Timberborn.*, Bindito.*

**Comment by thomaswp** [comment]
Ok, thanks for clarifying. Just for my own understanding, I see your [NuGet package](https://www.nuget.org/packages/TimberApi#dependencies-body-tab) references [Timberborn.GameLibs](https://www.nuget.org/packages/Timberborn.GameLibs/), but that's not hosted on NuGet. Where does it exist and who puts it out? Is it the devs themselves?

**Comment by KYPremco** [comment]
> Ok, thanks for clarifying. Just for my own understanding, I see your [NuGet package](https://www.nuget.org/packages/TimberApi#dependencies-body-tab) references [Timberborn.GameLibs](https://www.nuget.org/packages/Timberborn.GameLibs/), but that's not hosted on NuGet. Where does it exist and who puts it out? Is it the devs themselves? Since mine is out of date, just curious if/how I can update it.

https://nuget.bepinex.dev/packages/Timberborn.GameLibs
We upload it ourselves

**Comment by thomaswp** [comment]
Got it, thanks! And it looks like this was fixed in 0.5.7, so I appreciate the update.
