### ISSUE TITLE
error I dont know what is causing this 

### ISSUE THREAD

**Issue by TheGuardianTim** [Timberborn-Modding-Central/TimberAPI#99]
Mono path[0] = 'E:/SteamLibrary/steamapps/common/Timberborn/Timberborn_Data/Managed'
Mono config path = 'E:/SteamLibrary/steamapps/common/Timberborn/MonoBleedingEdge/etc'
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Timberborn/Timberborn_Data/MonoBleedingEdge/data-00000265A0785FF0.dll
Fallback handler could not load library E:/SteamLibrary/steamapps/common/Timberborn/Timberborn_Data/MonoBleedingEdge/data-00000265A6C4B040.dll
[Physics::Module] Initialized MultithreadedJobDispatcher with 15 workers.
Initialize engine version: 2023.1.20f1 (35a524b12060)
[Subsystems] Discovering subsystems at path E:/SteamLibrary/steamapps/common/Timberborn/Timberborn_Data/UnitySubsystems
Split Graphics Jobs are not supported on Direct3D 11. Reverting to Native Graphics Jobs instead.
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1660 SUPER (ID=0x21c4)
    Vendor:   NVIDIA
    VRAM:     5992 MB
    Driver:   30.0.15.1252
Begin MonoManager ReloadAssembly
- Loaded All Assemblies, in  0.435 seconds
- Finished resetting the current domain, in  0.001 seconds
[Message:   BepInEx] BepInEx 5.4.22.0 - Timberborn (1/20/2024 4:53:03 AM)
[Info   :   BepInEx] Running under Unity v2023.1.20.3515684
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Mod Manager UI 2.0.0]
[Info   :   BepInEx] Loading [TimberAPI BepInEx Entrypoint 1.0.0]
[Message:   BepInEx] Chainloader startup complete
<RI> Initializing input.
New input system (experimental) initialized
Using Windows.Gaming.Input
<RI> Initialized touch support.
UnloadTime: 0.679800 ms
Starting game version 0.5.9.1-33dabbc-sw
System info:
System: Windows 11  (10.0.22631) 64bit
CPU: AMD Ryzen 7 3700X 8-Core Processor 
GPU: NVIDIA GeForce GTX 1660 SUPER
GPU memory: 5992MB
RAM: 32629MB
Drives:
  C:\ 129.14GB free from 237.23GB
  D:\ 931.26GB free from 931.39GB
  E:\ 11895.89GB free from 13038.98GB
Modded: true, BepInEx
[Info   :TimberAPI Core] TimberAPI 0.6.3.1 - Timberborn 0.5.9.1, loader: BepInEx
[Info   : TimberAPI] Mod loading started
[Info   : TimberAPI] Found 0 mods
[Info   : TimberAPI] Deserialized 0 mods
[Info   : TimberAPI] Mod loading finished in: 7ms, Loaded mods:0
[Info   : TimberAPI] Added 1 prefixes
Successfully connected to the Steam client.
[Info   :Mod Manager UI] Loaded 34 custom labels
[Info   : TimberAPI] Loaded 0 custom labels
[Info   : TimberAPI] Assets loaded for MainMenu, Total prefixes loaded: 1
Previous resolution: 1920 x 1080
New resolution 1920 x 1080
Display resolution: 1920 x 1080
Full screen: True
Graphics quality: Ultra
Resolution scale: 1
[Error  :Mod Manager UI] Sharing violation on path E:\SteamLibrary\steamapps\common\Timberborn\BepInEx\plugins\modmanager_2.0.0-fmej\ModManager\temp\2671489_0.8.8.zip
First uncaught exception at 2024-04-06 14:37:06Z
Stopping all root objects in active scene
NullReferenceException: Object reference not set to an instance of an object
  at ModManagerUI.Components.ModFullInfo.DownloadButton.Refresh () [0x00045] in <e9502ac3153647d4a6f346e4db73ae85>:0 
  at ModManagerUI.Components.ModFullInfo.DownloadButton.Download () [0x00079] in <e9502ac3153647d4a6f346e4db73ae85>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <cb3602b5bf2148caa08db7780ec02b19>:0 
  at UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () [0x00002] in <fe5da7bf138e4fe086b7b29cbdb30e52>:0 
  at UnityEngine.UnitySynchronizationContext.Exec () [0x0005d] in <fe5da7bf138e4fe086b7b29cbdb30e52>:0 
  at UnityEngine.UnitySynchronizationContext.ExecuteTasks () [0x00014] in <fe5da7bf138e4fe086b7b29cbdb30e52>:0 

Unloading 7 Unused Serialized files (Serialized files now loaded: 2)
UnloadTime: 3.761500 ms
[Info   :Mod Manager UI] Loaded 34 custom labels
[Info   : TimberAPI] Loaded 0 custom labels
Creating an error report: C:\Users\timot\OneDrive\Documents\Timberborn\Error reports\error-report-2024-04-06-14h37m07s.zip

here is the other log if needed

v0.5.9.1-33dabbc-sw
NullReferenceException: Object reference not set to an instance of an object
ModManagerUI.Components.ModFullInfo.DownloadButton.Refresh () (at <e9502ac3153647d4a6f346e4db73ae85>:0)
ModManagerUI.Components.ModFullInfo.DownloadButton.Download () (at <e9502ac3153647d4a6f346e4db73ae85>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <cb3602b5bf2148caa08db7780ec02b19>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <fe5da7bf138e4fe086b7b29cbdb30e52>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <fe5da7bf138e4fe086b7b29cbdb30e52>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <fe5da7bf138e4fe086b7b29cbdb30e52>:0)

**Comment by TheGuardianTim** [comment]
I tried removing every mod and installing every mod still simular result

**Comment by KYPremco** [comment]
Likely not an issue with TimberAPI but mod manager, which does not use TimberAPI as a dependency. In need for active help setting up a modding enviroment to play on ask on the Timberborn discord.
